name: 'OpenAPI'
api: '1.0.0'
version: '1.0.0'
description: 'Open API for people who want help with BedrockPlay development'
author: 'VixikHD'
main: eu.happybe.openapi.OpenAPI

permissions:
  happybe.voter:
    description: 'Permission for people who voted'
    default: 'op'
  happybe.operator:
    default: 'op'
    description: 'Permissions for Owners, Developers and Admins'
    children:
      happybe.moderator:
        default: 'op'
        description: 'Permissions for Moderators'
        children:
          happybe.helper: # Yes, helper hasn't Bedrock rank permissions
            default: 'op'
            description: 'Permissions for Helpers'
          happybe.builder:
            default: 'op'
            description: 'Permissions for Builders'
            children:
              happybe.youtube:
                default: 'op'
                description: 'Permissions for people with YOUTUBE rank'
                children:
                  happybe.bedrock:
                    default: 'op'
                    description: 'Permissions for people with BEDROCK rank'
                    children:
                      happybe.mvp:
                        default: 'op'
                        description: 'Permissions for people with MVP rank'
                        children:
                          happybe.vip:
                            default: 'op'
                            description: 'Permissions for people with VIP'